### PR TITLE
chart

### PR DESCRIPTION
**Pull request by shuo-wu**

### CODE REVIEW

**Comment by yasker** [comment]
Just `/chart/`, not `/chart/latest`, since we don't keep version here.

**Comment by yasker** [comment]
In fact, let's move the chart to Longhorn repo. The README contains doc information which is in the Longhorn repo. So we don't need to sync from Longhorn repo then sync this back.

**Comment by shuo-wu** [comment]
How about directory of the script?

**Comment by yasker** [comment]
Oh no, that's only for build scripts. And the chart is not even a script.

**Comment by yasker** [comment]
@shuo-wu  In fact, which scripts you're talking about?

**Comment by shuo-wu** [comment]
see last commit. version update script.

**Comment by yasker** [comment]
That script is not a part of the chart. It's more like a release tool. You don't need to check it in, at least before other release tools checked in.

**Pull request closed without merging**
