### PR TITLE
iSCSI frontend support

### PR DESCRIPTION
**Pull request by yasker**

### CODE REVIEW

**Comment by yasker** [comment]
@LLParse Can you give this a try to see if it works for you?

**Comment by yasker** [comment]
@LLParse That looks about right. Found this format from [QEmu doc](https://qemu.weilnetz.de/doc/2.12/qemu-doc.html#disk_005fimages_005fiscsi):

```
URL syntax:
iscsi://[<username>[%<password>]@]<host>[:<port>]/<target-iqn-name>/<lun>
```
Do you have to had second `:` in unicode? That may looks weird in API.

**Comment by yasker** [comment]
@LLParse I've updated the format of the endpoint.

**Comment by LLParse** [comment]
@yasker LGTM

**Pull request merged**
